/*
Cyclical figurate numbers
Problem 61
Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:
Triangle	 	P3,n=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Square	 		P4,n=n2	 			1, 4, 9, 16, 25, ...
Pentagonal	 	P5,n=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	P6,n=n(2n−1)	 	1, 6, 15, 28, 45, ...
Heptagonal	 	P7,n=n(5n−3)/2	 	1, 7, 18, 34, 55, ...
Octagonal	 	P8,n=n(3n−2)	 	1, 8, 21, 40, 65, ...
The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.
The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
This is the only set of 4-digit numbers with this property.
Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.
*/
#include<iostream>
#include<ctime>
#include<vector>
#include<fstream>
#include<algorithm>
using namespace std;
int IsTri(int x) { return (-1 + sqrt(1 + 8 * x)) / 2 == (int)(-1 + sqrt(1 + 8 * x)) / 2 ? 3 : 0; }
int IsSqu(int x) { return sqrt(x) == (int)sqrt(x) ? 4 : 0; }
int IsPen(int x) { return (1 + sqrt(1 + 24 * x)) / 6 == (int)(1 + sqrt(1 + 24 * x)) / 6 ? 5 : 0; }
int IsHex(int x) { return (1 + sqrt(1 + 8 * x)) / 4 == (int)(1 + sqrt(1 + 8 * x)) / 4 ? 6 : 0; }
int IsHep(int x) { return (3 + sqrt(9 + 40 * x)) / 10 == (int)(3 + sqrt(9 + 40 * x)) / 10 ? 7 : 0; }
int IsOct(int x) { return (2 + sqrt(4 + 12 * x)) / 6 == (int)(2 + sqrt(4 + 12 * x)) / 6 ? 8 : 0; }
int Is(int x)
{
	if (IsTri(x))return 3;
	if (IsSqu(x))return 4;
	if (IsPen(x))return 5;
	if (IsHex(x))return 6;
	if (IsHep(x))return 7;
	if (IsOct(x))return 8;
}
vector<int> GetArr(int x, int y, int (*check)(int))
{
	vector<int> a;
	for (int num = x; num <= y; num++)
	{
		if (check(num))
		{
			a.push_back(num);
		}
	}
	return a;
}
vector<int> arr()
{
	vector<int> a;
	for (int i = 1000; i <= 9999; i++)
	{
		if (IsTri(i) || IsSqu(i) || IsPen(i) || IsHex(i) || IsHep(i) || IsOct(i))
		{
			a.push_back(i);
		}
	}
	return a;
}
int main()
{
	clock_t start = clock();
	vector<int> P3 = GetArr(1000, 9999, &IsTri); //96
	vector<int> P4 = GetArr(1000, 9999, &IsSqu); //68
	vector<int> P5 = GetArr(1000, 9999, &IsPen); //56
	vector<int> P6 = GetArr(1000, 9999, &IsHex); //48
	vector<int> P7 = GetArr(1000, 9999, &IsHep); //43
	vector<int> P8 = GetArr(1000, 9999, &IsOct); //40

	vector<int> a = arr();
	for (int i = 0; i < P3.size(); i++)
	{
		cout << Is(P4[i]) << endl;
	}

	clock_t end = clock();
	cout << "done in " << (double)(end - start) * 1000 / CLOCKS_PER_SEC << "ms" << endl;
	
	system("pause");
	return 0;
}