/*Pentagon numbers
Problem 44
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?*/

#include<iostream>
#include<algorithm>
#include<string>
#include<vector>
#include<ctime>
using namespace std;
bool IsPentagon(int p)
{
	return (1 + sqrt(1 + 24 * p)) / 6 == (int)(1 + sqrt(1 + 24 * p)) / 6;
}
int main()
{
	clock_t t = clock();
	int n = 1;
	while (true)
	{
		for (int i = 1; i <= n - 2; i++)
		{
			int Pk = (i + 1) * (3 * (i + 1) - 1) / 2;
			int Pj = n *(3 * n - 1) / 2 - Pk;
			if (IsPentagon(Pk) && IsPentagon(Pj) && IsPentagon(Pk - Pj))
			{
				cout << Pk - Pj;
				goto finish;
			}
		}
		n++;
	}
finish:
	t = clock() - t;
	cout << " done in " << (double)t / CLOCKS_PER_SEC << endl;
	system("pause");
	return 0;
}