/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
Mỗi thuật ngữ mới trong dãy Fibonacci được tạo ra bằng cách thêm hai thuật ngữ trước đó.Bắt đầu bằng 1 và 2, 10 điều khoản đầu tiên sẽ là :
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Bằng cách xem xét các thuật ngữ trong dãy Fibonacci có giá trị không vượt quá bốn triệu, hãy tìm tổng của các thuật ngữ có giá trị.*/

#include <iostream>
using namespace std;

int Fibonacci(int);

int main()
{
	int sum = 0, f_0 = 0, f_1 = 1, f_n = 1;
	while (f_n < 4000000)
	{
		if (f_n % 2 == 0)
		{
			sum += f_n;
		}
		f_0 = f_1;
		f_1 = f_n;
		f_n = f_0 + f_1;
	}
	cout << sum;
	system("pause");
	return 0;
}

int Fibonacci(int x)
{
	int f_0 = 0;
	int f_1 = 1;
	int f_n = 1;
	for (int i = 1; i <= x; i++)
	{
		f_n = f_0 + f_1;
		f_0 = f_1;
		f_1 = f_n;
	}
	return f_n;
}
