/*
Triangular, pentagonal, and hexagonal
Problem 45
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.
*/
#include<iostream>
#include<vector>
#include<ctime>
using namespace std;
bool IsTriangle(long long T)
{
	return (sqrt(1 + 8 * T) - 1) / 2 == (long long)(sqrt(1 + 8 * T) - 1) / 2;
}
bool IsPentagonal(long long P)
{
	return (1 + sqrt(1 + 24 * P)) / 6 == (long long)(1 + sqrt(1 + 24 * P)) / 6;
}
bool IsHexagonal(long long H)
{
	return (1 + sqrt(1 + 8 * H)) / 4 == (long long)(1 + sqrt(1 + 8 * H)) / 4;
}
int main()
{
	clock_t t = clock();
	long long n = 286;
	while (n++)
	{
		//cout << n << endl;
		long long T = n * (n + 1) / 2;
		if (IsPentagonal(T) && IsHexagonal(T))
		{
			cout << T;
			break;
		}
	}
	t = clock() - t;
	cout << " done in " << (double)t / CLOCKS_PER_SEC << endl;
	system("pause");
	return 0;
}